"""seguidores

Revision ID: 860a26c9d951
Revises: f2494b104b5a
Create Date: 2020-05-27 21:29:09.007572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860a26c9d951'
down_revision = 'f2494b104b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
